Markdown: Resume, Presentation.
iitpkd/templates pull request #4
Opened 2018-10-23 16:06 UTC by ashutosh2411

Templates for Resume and Presentation added. 
Instructions and tools to generate PDFs and Presentations included in README.
ToDo: templates for Reports.

2018-10-24 03:32 UTC, piyush-kurur commented
For each template in format `foo` I have followed the convention that all the relevant files are kept
in the directory `foo/name_of_the_template/` (note it is a directory and not a file). This way any one who wants to work on a document can copy the directory,  put it under version control, and start editing. This directory is also the right place to put a readme on any special instructions needed for
the format. 

Please follow that convention.

Also there is no point in adding the official template from a project; you can as well point to that. Rather
what you would want are tweaks specific to IIT Palakkad. For example, there is no point in keeping
a `reports.cls` file in this repository. However, it might make sense to configure it appropriately so that
a student can use the latex files there (together with supporting files like a make file and a set of custom macros).

2018-10-24 03:39 UTC, piyush-kurur requested changes

2018-10-24 03:39 UTC, piyush-kurur commented on markdown/resume.md
> +* __Project 1:__ _(Jan, 2018 - Feb, 2018)_ Designed and implemented a Hashing protocol in Haskell for encrypting and decrypting messages on LAN. Find the implementation [here](github.com).
I can see that this is one of your projects. I would prefer a fictitious project (some joke project is better).

2018-10-24 03:39 UTC, piyush-kurur commented on markdown/resume.md
> +* __Software Developer Intern @AgniCool:__ _(May 2018- July 2018)_ Worked in agile environment. [Here](google.com) is a link to Google's home page.
Same here, Joke projects are encouraged.

2018-10-24 09:18 UTC, ashutosh2411 commented
The repository structure has been modified 
The slides template has been tweaked
Internship reports and project reports have been updated.

2018-10-26 13:42 UTC, closed without merging

2018-10-27 08:51 UTC, piyush-kurur commented
I will merge this at some point of time.In response to review message you just need to keep pushing on to the same branch. You do not have to close.